name: Build and Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push:
    runs-on: docker

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Forgejo Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login git.june.pet -u "${{ github.actor }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t git.june.pet/june/goto:${{ github.sha }} -t git.june.pet/june/goto:latest .
          docker push git.june.pet/june/goto:${{ github.sha }}
          docker push git.june.pet/june/goto:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add SSH private key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Apply
        working-directory: terraform
        run: |
          terraform init
          terraform apply -auto-approve
        env:
          TF_VAR_r2_access_key:  ${{ secrets.R2_ACCESS_KEY }}
          TF_VAR_r2_access_secret: ${{ secrets.R2_ACCESS_SECRET }}
          TF_VAR_docker_host:    ${{ vars.DOCKER_HOST }}
          TF_VAR_docker_user:    ${{ vars.DOCKER_USER }}
          TF_VAR_image_tag:      ${{ github.sha }}
          TF_VAR_r2_endpoint:    ${{ vars.R2_ENDPOINT }}
