name: Build and Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Add SSH private key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ./private.key
          chmod 600 ./private.key

      - name: Run Docker Compose
        env:
          SERVER_IP: ${{ vars.SERVER_IP }}
        run: ssh -o "StrictHostKeyChecking no" -i ./private.key june@$SERVER_IP "cd ~/goto && git pull && docker compose up -d --build"