// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alias.sql

package sqlc

import (
	"context"
)

const createAlias = `-- name: CreateAlias :one
INSERT INTO alias (name, destination_id)
VALUES (?, ?)
RETURNING id, name, destination_id
`

type CreateAliasParams struct {
	Name          string `json:"name"`
	DestinationID int64  `json:"destination_id"`
}

func (q *Queries) CreateAlias(ctx context.Context, arg CreateAliasParams) (Alias, error) {
	row := q.db.QueryRowContext(ctx, createAlias, arg.Name, arg.DestinationID)
	var i Alias
	err := row.Scan(&i.ID, &i.Name, &i.DestinationID)
	return i, err
}

const deleteAliasByID = `-- name: DeleteAliasByID :exec
DELETE FROM Alias
WHERE id = ?
`

func (q *Queries) DeleteAliasByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAliasByID, id)
	return err
}

const listAliases = `-- name: ListAliases :many
SELECT id, name, destination_id FROM alias
`

func (q *Queries) ListAliases(ctx context.Context) ([]Alias, error) {
	rows, err := q.db.QueryContext(ctx, listAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alias
	for rows.Next() {
		var i Alias
		if err := rows.Scan(&i.ID, &i.Name, &i.DestinationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAliasesByDestinationId = `-- name: ListAliasesByDestinationId :many
SELECT id, name, destination_id FROM alias
WHERE destination_id = ?
`

func (q *Queries) ListAliasesByDestinationId(ctx context.Context, destinationID int64) ([]Alias, error) {
	rows, err := q.db.QueryContext(ctx, listAliasesByDestinationId, destinationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alias
	for rows.Next() {
		var i Alias
		if err := rows.Scan(&i.ID, &i.Name, &i.DestinationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAliasByID = `-- name: UpdateAliasByID :one
UPDATE alias
SET name = ?, destination_id = ?
WHERE id = ?
RETURNING id, name, destination_id
`

type UpdateAliasByIDParams struct {
	Name          string `json:"name"`
	DestinationID int64  `json:"destination_id"`
	ID            int64  `json:"id"`
}

func (q *Queries) UpdateAliasByID(ctx context.Context, arg UpdateAliasByIDParams) (Alias, error) {
	row := q.db.QueryRowContext(ctx, updateAliasByID, arg.Name, arg.DestinationID, arg.ID)
	var i Alias
	err := row.Scan(&i.ID, &i.Name, &i.DestinationID)
	return i, err
}
