// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type Alias struct {
	ID            int64  `json:"id"`
	Name          string `json:"name"`
	DestinationID int64  `json:"destination_id"`
}

type Destination struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Url  string `json:"url"`
}
