// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
)

const createDestination = `-- name: CreateDestination :one
INSERT INTO destination (name, url)
VALUES (?, ?)
RETURNING id, name, url
`

type CreateDestinationParams struct {
	Name string `json:"name"`
	Url  string `json:"url"`
}

func (q *Queries) CreateDestination(ctx context.Context, arg CreateDestinationParams) (Destination, error) {
	row := q.db.QueryRowContext(ctx, createDestination, arg.Name, arg.Url)
	var i Destination
	err := row.Scan(&i.ID, &i.Name, &i.Url)
	return i, err
}

const deleteDestinationByID = `-- name: DeleteDestinationByID :exec
DELETE FROM destination
WHERE id = ?
`

func (q *Queries) DeleteDestinationByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDestinationByID, id)
	return err
}

const getDestinationByID = `-- name: GetDestinationByID :one
SELECT id, name, url FROM destination
WHERE id = ?
`

func (q *Queries) GetDestinationByID(ctx context.Context, id int64) (Destination, error) {
	row := q.db.QueryRowContext(ctx, getDestinationByID, id)
	var i Destination
	err := row.Scan(&i.ID, &i.Name, &i.Url)
	return i, err
}

const listDestinations = `-- name: ListDestinations :many
SELECT id, name, url FROM destination
`

func (q *Queries) ListDestinations(ctx context.Context) ([]Destination, error) {
	rows, err := q.db.QueryContext(ctx, listDestinations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Destination
	for rows.Next() {
		var i Destination
		if err := rows.Scan(&i.ID, &i.Name, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
